name: Build and Deploy to Hostinger

on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "22.5.1"

      - name: Install dependencies
        run: npm install

      - name: Build the project
        run: npm run build

      - name: Deploy to Server via scp
        env:
          SERVER_HOST: ${{ secrets.SERVER_HOST }}
          SERVER_USER: ${{ secrets.SERVER_USER }}
          SERVER_PORT: ${{ secrets.SERVER_PORT }}
          SERVER_PATH: ${{ secrets.SERVER_PATH }}
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          ssh-keyscan -p $SERVER_PORT $SERVER_HOST >> ~/.ssh/known_hosts
          chmod 600 private_key.pem
          scp -P $SERVER_PORT -i private_key.pem -r ./out/* $SERVER_USER@$SERVER_HOST:$SERVER_PATH
          scp -P 65002 -i private_key.pem -r ./out/* u621401600@91.108.101.231:$SERVER_PATH
          scp -P 65002 -r ./out/* u621401600@91.108.101.231:domains/snow-dugong-435469.hostingersite.com/public_html/
          rm private_key.pem
